# Generated by Django 5.1.6 on 2025-05-13 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockeddate',
            options={},
        ),
        migrations.RenameField(
            model_name='blockeddate',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='blockeddate',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='blockeddate',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
