# Generated by Django 5.1.6 on 2025-05-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser_portal', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
