# Generated by Django 5.1.6 on 2025-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser_portal', '0003_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeddate',
            name='end_time',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
