# Generated by Django 5.1.6 on 2025-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0006_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_upload',
            field=models.FileField(blank=True, null=True, upload_to='id_uploads/'),
        ),
    ]
