# Generated by Django 5.1.6 on 2025-05-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0009_reservation_amount_reservation_billing_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='billing_file',
            field=models.FileField(blank=True, null=True, upload_to='billing/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
