# Generated by Django 5.1.6 on 2025-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0010_alter_reservation_billing_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
