# Generated by Django 5.1.6 on 2025-05-21 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Admin Approved', 'Admin Approved'), ('Billing Uploaded', 'Billing Uploaded'), ('Payment Pending', 'Payment Pending'), ('Payment Approved', 'Payment Approved'), ('Security Pass Issued', 'Security Pass Issued'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_approvals', models.JSONField(blank=True, default=dict)),
                ('admin_rejections', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='00:00:00')),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('reasons', models.TextField(blank=True)),
                ('billing_statement', models.FileField(blank=True, null=True, upload_to='billing_statements/')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('security_pass', models.FileField(blank=True, null=True, upload_to='passes/')),
                ('security_pass_returned', models.FileField(blank=True, null=True, upload_to='security_passes/')),
                ('security_pass_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('security_pass_rejection_reason', models.TextField(blank=True, null=True)),
                ('facility_use', models.CharField(blank=True, max_length=255)),
                ('date_reserved', models.DateField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('representative', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('insider_count', models.IntegerField(default=0)),
                ('outsider_count', models.IntegerField(default=0)),
                ('facilities_needed', models.JSONField(blank=True, default=dict)),
                ('manpower_needed', models.JSONField(blank=True, default=dict)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_verified_date', models.DateTimeField(blank=True, null=True)),
                ('payment_rejection_reason', models.TextField(blank=True, null=True)),
                ('dates', models.JSONField(blank=True, default=list)),
                ('facilities', models.ManyToManyField(related_name='reservations', to='superuser_portal.facility')),
                ('payment_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
