# Generated by Django 5.1.6 on 2025-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='facilities_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='insider_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='manpower_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='outsider_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='representative',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.CharField(max_length=255),
        ),
    ]
