# Generated by Django 5.1.6 on 2025-05-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_options_reservation_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reasons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
