# Generated by Django 5.1.6 on 2025-05-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_contact_number_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reasons',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='title',
        ),
    ]
