# Generated by Django 5.1.6 on 2025-05-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_contact_number_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_reserved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='facility_use',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='facilities_needed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='manpower_needed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
