# Generated by Django 5.1.6 on 2025-05-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservation_date_reserved_reservation_facility_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time_slot',
        ),
    ]
