# Generated by Django 5.1.6 on 2025-05-22 05:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservation_reserved_dates'),
    ]

    operations = [
        # The following ArrayFields are not supported in SQLite and cause migration errors
        # migrations.AddField(
        #     model_name='reservation',
        #     name='payment_receipts',
        #     field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='receipts/'), blank=True, default=list, help_text='Multiple payment receipts.', null=True, size=None),
        # ),
        # migrations.AddField(
        #     model_name='reservation',
        #     name='security_pass_returned_files',
        #     field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='security_passes/'), blank=True, default=list, help_text='Multiple returned security pass files.', null=True, size=None),
        # ),
    ]
