# Generated by Django 5.1.6 on 2025-05-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_remove_reservation_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='admin_approvals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reservation',
            name='admin_rejections',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approval_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rejection_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved for Billing', 'Approved for Billing'), ('Billing Released', 'Billing Released'), ('Payment Submitted', 'Payment Submitted'), ('Payment Approved', 'Payment Approved'), ('Payment Rejected', 'Payment Rejected'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
