# Generated by Django 5.1.6 on 2025-05-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_reservation_payment_receipts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment_receipts',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='security_pass_returned_files',
        ),
    ]
