# Generated by Django 5.1.6 on 2025-05-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_remove_reservation_payment_receipts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='letter',
            field=models.FileField(blank=True, null=True, upload_to='letters/'),
        ),
    ]
