# Generated by Django 5.1.6 on 2025-05-04 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='time_end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time_start',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_reserved',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='facilities_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='facility_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='insider_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='manpower_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='organization',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='outsider_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='representative',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='facility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('facility', 'date', 'start_time', 'end_time')},
        ),
    ]
