# Generated by Django 5.1.6 on 2025-05-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0003_rename_time_end_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='facilities_needed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='manpower_needed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
