# Generated by Django 5.1.6 on 2025-05-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0004_reservation_notification_otherfacility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
