# Generated by Django 5.1.6 on 2025-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0005_profile_profile_picture_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student of XU', 'Student of XU'), ('Alumni/Guest', 'Alumni/Guest')], default='Student of XU', max_length=20),
        ),
    ]
