# Generated by Django 5.1.6 on 2025-05-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
