# Generated by Django 5.1.6 on 2025-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0009_reservation_amount_reservation_billing_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='completed_form',
            field=models.FileField(blank=True, null=True, upload_to='completed_forms/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='security_pass_id',
            field=models.CharField(default='R-1', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='security_pass_pdf',
            field=models.FileField(blank=True, null=True, upload_to='security_passes/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='billing_file',
            field=models.FileField(blank=True, null=True, upload_to='billing/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
