# Generated by Django 5.1.6 on 2025-05-12 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0012_reservation_updated_at_alter_reservation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'date', 'start_time', 'end_time')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='facility',
        ),
    ]
