# Generated by Django 5.1.6 on 2025-05-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0013_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='security_pass_file',
            field=models.FileField(blank=True, null=True, upload_to='security_passes/'),
        ),
    ]
