# Generated by Django 5.1.6 on 2025-05-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0014_reservation_security_pass_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
