# Generated by Django 5.1.6 on 2025-05-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0015_reservation_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment_receipt',
        ),
    ]
