# Generated by Django 5.1.6 on 2025-05-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0016_remove_reservation_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='completed_security_form',
            field=models.FileField(blank=True, null=True, upload_to='completed_security_forms/'),
        ),
    ]
